[build.environment]
HUGO_VERSION = "0.54.0"

[context.production.environment]
HUGO_VERSION = "0.54.0"

[context.deploy-preview]
command = "hugo -b $DEPLOY_PRIME_URL --buildFuture"
HUGO_VERSION = "0.54.0"

[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL --buildFuture"
HUGO_VERSION = "0.54.0"
